version: '3.4'

services:
    recipe-database:
         image: postgres:latest
         restart: always
         environment:
             POSTGRES_USER: test
             POSTGRES_PASSWORD: test
             POSTGRES_DB: recipedb
         ports:
            - 5435:5432
         volumes:
           - dataRecipe:/var/lib/postgresql/data
    recipe-write-service:
        image: recipewriteservice:latest
        ports:
            - 8083:443
            - 8084:80
        build:
            context: recipe-write-service
            dockerfile: recipe-write-service/Dockerfile
        depends_on:
            - "recipe-database"
        environment:
            DB_CONNECTION_STRING: "host=recipe-database;port=5432;database=recipedb;username=test;password=test"
    recipe-read-service:
        image: recipereadservice:latest
        ports:
            - 8081:443
            - 8082:80
        build:
            context: recipe-read-service
            dockerfile: recipe-read-service/Dockerfile
        depends_on:
            - "recipe-database"
        environment:
            DB_CONNECTION_STRING: "host=recipe-database;port=5432;database=recipedb;username=test;password=test"
    
volumes:
    dataRecipe: