trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - recipe-write-service/**
    - .github/workflows/recipe-write-service.yml

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '1de275c2-066a-4241-b863-53525d7d2836'
  imageRepository: 'recipewriteservice'
  containerRegistry: 'kruimlcontainerregister.azurecr.io/recipewriteservice:latest'
  dockerfilePath: './recipe-write-service/recipe-write-service/Dockerfile'
  tag: 'latest'
  imagePullSecret: 'kruimlcontainerregister3c34-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        buildContext: recipe-write-service
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'Azure for Students(22fae281-192f-4d7e-a431-690531f59669)'
        azureResourceGroup: 'kruimlResourceGroup'
        kubernetesCluster: 'kruimlCluster'
        command: 'apply'
        arguments: '-f ./k8s/recipe-write-service.yaml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'