apiVersion : apps/v1
kind: Deployment
metadata:
  name: recipereadservice 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipereadservice
  template:
    metadata:
      labels:
        app: recipereadservice 
    spec:
      containers:
        - name: recipereadservice 
          image: kruimlcontainerregister.azurecr.io/recipereadservice
          ports:
          - containerPort: 80