version: '3.4'

networks:
    recipe-service-dev:
        driver: bridge

services:
    recipe-database:
         image: postgres:latest
         restart: always
         environment:
             POSTGRES_USER: test
             POSTGRES_PASSWORD: test
             POSTGRES_DB: recipedb
         ports:
            - 5432:5432
         volumes:
           - pgdata:/var/lib/postgresql/data
           - ./Repository/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
         networks:
            - recipe-service-dev
    recipe-service:
        image: recipeservice:latest
        ports:
            - 8081:443
            - 8082:80
        build:
            context: .
            dockerfile: recipe-service/Dockerfile
        depends_on:
            - "recipe-database"
        networks:
            - recipe-service-dev
        environment:
            DB_CONNECTION_STRING: "host=recipe-database;port=5432;database=recipedb;username=test;password=test"

volumes:
    pgdata: